### ISSUE TITLE
gaps/0-length overlaps

### ISSUE THREAD

**Issue by MihaiPop** [thegenemyers/DAS-SPEC#1]
Following up on a discussion we've had in the GFA/GFA2 debate - would you want segments butting end to end to be represented in the E records (... $ $ ^ ^ ) or in the G records. If the latter, we may have to adjust the semantics of the gap size to make this work - currently the spec says that a size of 0 indicates "gap of unknown size".  Could we have "0 0" (size stdev) mean "size is exactly 0"?  Also, what should a standard deviation of 0 mean? I'd favor "size is exact" (in some cases we may know the exact gap size), but then we won't be able to record "unknown stdev".  

Another solution would be to use a symbol (such as *) to indicate unknown values.

**Comment by thegenemyers** [comment]
Hi Mihai,

```
In my framework G edges are springs that inherently variable, E 
```

edges are definitive relationships
(albeit they can be 0 length).  So the former, E edges with $ $ ^ ^, or 
-1 -1 0 0 in the new proposal.
That leaves 0 for the variance as "I don't know" (which is important as 
a number of technologies don't
give you an estimate of accuracy (e.g. Hi-C)).

```
-- Gene
```

**Comment by MihaiPop** [comment]
Works for me, though it will have to be clarified in the spec. I'd be happy to make the change but don't want to step on your toes.  Also - is this where development will continue or are we back at GFA2?

**Comment by thegenemyers** [comment]
Mihai,

```
I will soon make a pull request at the GFA site and presumably that 
```

is were we will
go forward in public.

```
-- Gene
```
